config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :characters
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  belongs_to :race
  belongs_to :gender
  belongs_to :profession
end

app/models/gender.rb
class Gender < ApplicationRecord
  has_many :characters
end

app/models/profession.rb
class Profession < ApplicationRecord
  has_many :characters
end

app/models/race.rb
class Race < ApplicationRecord
  has_many :characters
end

app/models/user.rb
class User < ApplicationRecord
  has_many :characters, dependent: :destroy
  has_many :races, through: :characters

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :user_id, only: [:new, :create, :index, :edit]
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  def index
    redirect_to user_path(@user)
  end

  def show
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)
    @character.user = @user
    if @character.save
      redirect_to user_path(@character.user)
    else
      render :new
    end
  end

  def edit

  end

  def update
    @character.update(character_params)
    @character.save
    redirect_to user_path(@character.user)
  end

  def destroy
    @character.destroy
    redirect_to user_path(@character.user)
  end

  private

  def set_character
    @character = Character.find(params[:id])
  end

  def character_params
    params.require(:character).permit(
      :name,
      :description,
      :allies,
      :enemies,
      :race_id,
      :gender_id,
      :profession_id
      )
  end

  def user_id
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy, :update, :edit]

  def index
    @users = User.all
  end

  def show
    # @chars = @user.characters
    # render :json => @chars
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path(@user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/characters/edit.html.erb
<div class="hund-container" style="background-image: url(<%= image_url("tavern.jpg") %>);"> >
  <div class="character-form-container" style=" background-image: linear-gradient(to right, rgba(0,0,0,0.2),rgba(0,0,0,0.1)), url(<%= image_url("small-tome-page.png") %>">
  <div class="user-form-container">
    <h1 class="styled-font">Tell us about your new legendary figure!</h1>
    <%= simple_form_for [@user, @character], class:"font-whites" do |f| %>
    <%= f.input :name, label_html: { class:"font-white font-bigger shadow" }%>
    <%= f.input :allies, label_html: { class:"font-white font-bigger shadow" } %>
    <%= f.input :enemies, label_html: { class:"font-white font-bigger shadow" } %>
    <%= f.input :description, label_html: { class:"font-white font-bigger shadow" }, input_html: {rows: 5} %>
    <%= f.association :race, label_method: :value, label_html: { class:"font-white font-bigger shadow" } %>
    <%= f.association :gender, label_method: :gender_value, label_html: { class:"font-white font-bigger shadow" } %>
    <%= f.association :profession, label_method: :job, label_html: { class:"font-white font-bigger shadow" } %>
    <div class="flx-container space-between">
    <%= f.button :submit, class:"dbtn-ghost" %>
    <%= link_to "return", user_path(@user), class:"dbtn-ghost" %>
    </div>
    <% end %>
  </div>
  </div>
</div>

app/views/characters/index.html.erb
<h1>THIS IS THE CHARACTERS of USER PAGE</h1>

<% @chars.each do |char| %>
  <%= char.name %>
  <%= link_to "edit me", edit_user_character_path %>
<br>
<br>

<%= link_to "home page", users_path %>

<% end %>

app/views/characters/new.html.erb
<div class="hund-container" style="background-image: url(<%= image_url("tavern.jpg") %>);"> >
  <div class="character-form-container" style=" background-image: linear-gradient(to right, rgba(0,0,0,0.2),rgba(0,0,0,0.1)), url(<%= image_url("small-tome-page.png") %>">
  <div class="user-form-container">
    <h1 class="styled-font">Tell us about your new legendary figure!</h1>
    <%= simple_form_for [@user, @character], class:"font-whites" do |f| %>
    <%= f.input :name, label_html: { class:"font-white font-bigger shadow" }%>
    <%= f.input :allies, label_html: { class:"font-white font-bigger shadow" } %>
    <%= f.input :enemies, label_html: { class:"font-white font-bigger shadow" } %>
    <%= f.input :description, label_html: { class:"font-white font-bigger shadow" }, input_html: {rows: 5} %>
    <%= f.association :race, label_method: :value, label_html: { class:"font-white font-bigger shadow" } %>
    <%= f.association :gender, label_method: :gender_value, label_html: { class:"font-white font-bigger shadow" } %>
    <%= f.association :profession, label_method: :job, label_html: { class:"font-white font-bigger shadow" } %>
    <div class="flx-container space-between">
    <%= f.button :submit, class:"dbtn-ghost" %>
    <%= link_to "return", user_path(@user), class:"dbtn-ghost" %>
    </div>
    <% end %>
  </div>
  </div>
</div>

app/views/characters/show.html.erb
<h1>This is the SINGLE character of USER page</h1>

<%= @character.name %>
<br>
<br>
<%= link_to "user-page", user_path(@character.user) %>
<br>
<br>
<%= link_to "edit me", edit_user_character_path %>
<br>
<br>

<%= link_to "home page", users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CharacterMaker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/shared/_nav-show.html.erb
<nav class="navbar navbar-light bg-transparent fixed-top">
  <%= link_to "Home", users_path, class:"navbar-brand text-white" %>
  <%= link_to "New Character", new_user_character_path(@user), class:"navbar-brand text-white" %>
</nav>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-transparent fixed-top">
  <%= link_to "Home", users_path, class:"navbar-brand text-white" %>
  <%= link_to "Join", new_user_path, class:"navbar-brand text-white" %>
</nav>

app/views/users/edit.html.erb
<div class="hund-container" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_url("tavern.jpg") %>);"> >
  <div class="user-form-container">
    <h1 class="styled-font">Tell us about yourself, Adventurer!</h1>
    <%= simple_form_for @user, class:"font-whites" do |f| %>
    <%= f.input :username, label_html: { class:"font-white font-bigger" }%>
    <%= f.input :password, label_html: { class:"font-white font-bigger" } %>
    <%= f.input :email, label_html: { class:"font-white font-bigger" } %>
    <div class="flx-container space-between">
    <%= f.button :submit, class:"dbtn-ghost" %>
    <%= link_to "return", users_path, class:"dbtn-ghost" %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'shared/nav' %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_url("Fantasy-banner.jpg") %>);">
  <div class="container">
    <h1>Character Maker</h1>
    <p>Click, Add, Play</p>
    <%= link_to "Start Now", new_user_path, class:"dbtn-ghost" %>
  </div>
</div>
<div class="bblack" style="width: 100vw">
  <div class="cards">
    <% @users.each do |user| %>
      <div>
        <div class="card-category" style="background-image: url(<%= image_url("male-face.jpg") %>);">
          <%= link_to user.username, user_path(user), class:"card-link" %>
          <%= link_to edit_user_path(user), class:"card-edit" do %>
            <i class="fas fa-edit"></i>
          <% end %>
          <%= link_to user_path(user), data: { confirm:"are you sure?" }, method: :delete, class:"card-delete" do %>
            <i class="fas fa-ban"></i>
          <% end %>
        </div>
      </div>
    <% end  %>
  </div>
</div>

app/views/users/new.html.erb
<div class="hund-container" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_url("tavern.jpg") %>);"> >
  <div class="user-form-container">
    <h1 class="styled-font">Tell us about yourself, Adventurer!</h1>
    <%= simple_form_for @user, class:"font-whites" do |f| %>
    <%= f.input :username, label_html: { class:"font-white font-bigger" }%>
    <%= f.input :password, label_html: { class:"font-white font-bigger" } %>
    <%= f.input :email, label_html: { class:"font-white font-bigger" } %>
    <div class="flx-container space-between">
    <%= f.button :submit, class:"dbtn-ghost" %>
    <%= link_to "return", users_path, class:"dbtn-ghost" %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'shared/nav-show' %>
<div class="hund-container" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_url("tavern.jpg") %>);"> >

  <div class="ninefivew-container">
    <!-- Text Goes here -->
    <div class="show-text text-center" s>
      <h1 class="styled-font">Welcome Adventurer!</h1>
      <h3 class="styled-font">Here lies <%= "#{@user.username}'s" %> tome of legends</h3>
      <p class="font-white font-lilbigger">Within these pages you shall find a story known only to a few</p>
    </div>
    <div class="display-boxes">
      <div><!-- Cards go in here-->
        <!-- Loop below -->
        <div class="cards-chars" >
          <% @user.characters.each do |char| %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_url("female-face.jpg") %>);">
            <%= char.name %>
            <%= link_to edit_user_character_path(@user, char), class:"card-edit" do %>
              <i class="fas fa-edit"></i>
            <% end %>
            <%= link_to user_character_path(@user, char), data: { confirm:"are you sure?" }, method: :delete, class:"card-delete" do %>
              <i class="fas fa-ban"></i>
            <% end %>
            </div>
          <% end  %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_url("female-face.jpg") %>);">
          <%= link_to "add a character", new_user_character_path(@user) %>
          </div>
        </div>
      </div>
        <!-- BIG char display goes here -->
      <div  class="eight-container" style="background-image: url(<%= image_url("tome-page.jpg") %>">
        <h1 >THIS IS FOR THE SINGLE CHARACTER DISPLAY</h1>
      </div>
    </div>

  </div>
</div>